
language: cpp
os: osx
osx_image: xcode8.2

script:
  - xcodebuild -scheme XcodeCITest -workspace XcodeCITest.xcodeproj/project.xcworkspace
#xcode_project: XcodeCITest.xcodeproj
#xcode_scheme: XcodeCITest
